/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Panel;

import ClassComponent.AccountData;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Admin
 */
public class Account extends javax.swing.JPanel {

    /**
     * Creates new form Account
     */
    private JPanel body,main;
    private AccountData acc = new AccountData();
    private thongtin_tk tt = new thongtin_tk();
    private HomeFrame home;
    public Account() {
        initComponents();
    }

    public void setBody(JPanel body) {
        this.body = body;
    }
    
    public void setMain(JPanel main)
    {
        this.main = main;
    }

    public void setAcc(AccountData acc) {
        this.acc = acc;
    }

    public void setHome(HomeFrame home) {
        this.home = home;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCustom1 = new ClassExtend.PanelCustom();
        panelCustom2 = new ClassExtend.PanelCustom();
        panelCustom3 = new ClassExtend.PanelCustom();

        setBackground(new java.awt.Color(0, 0, 0));
        setPreferredSize(new java.awt.Dimension(100, 46));

        panelCustom1.setBackgroundImage(acc.getURLAva());
        panelCustom1.setBackground(new java.awt.Color(255, 255, 204));
        panelCustom1.setOpaque(false);
        panelCustom1.setPreferredSize(new java.awt.Dimension(31, 31));
        panelCustom1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelCustom1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelCustom1Layout = new javax.swing.GroupLayout(panelCustom1);
        panelCustom1.setLayout(panelCustom1Layout);
        panelCustom1Layout.setHorizontalGroup(
            panelCustom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 31, Short.MAX_VALUE)
        );
        panelCustom1Layout.setVerticalGroup(
            panelCustom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 31, Short.MAX_VALUE)
        );

        panelCustom2.setBackgroundImage("C:\\Java\\FinalPresent\\src\\main\\java\\Icon\\gift.png");
        panelCustom2.setBackground(new java.awt.Color(204, 255, 204));
        panelCustom2.setOpaque(false);
        panelCustom2.setPreferredSize(new java.awt.Dimension(31, 31));
        panelCustom2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelCustom2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelCustom2Layout = new javax.swing.GroupLayout(panelCustom2);
        panelCustom2.setLayout(panelCustom2Layout);
        panelCustom2Layout.setHorizontalGroup(
            panelCustom2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 31, Short.MAX_VALUE)
        );
        panelCustom2Layout.setVerticalGroup(
            panelCustom2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 31, Short.MAX_VALUE)
        );

        panelCustom3.setBackground(new java.awt.Color(204, 204, 255));
        panelCustom3.setOpaque(false);
        panelCustom3.setPreferredSize(new java.awt.Dimension(31, 31));

        javax.swing.GroupLayout panelCustom3Layout = new javax.swing.GroupLayout(panelCustom3);
        panelCustom3.setLayout(panelCustom3Layout);
        panelCustom3Layout.setHorizontalGroup(
            panelCustom3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 31, Short.MAX_VALUE)
        );
        panelCustom3Layout.setVerticalGroup(
            panelCustom3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 31, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelCustom1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelCustom2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelCustom3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelCustom1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelCustom2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelCustom3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void panelCustom1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelCustom1MouseClicked
        // TODO add your handling code here:
        home.callUserFunction();
    }//GEN-LAST:event_panelCustom1MouseClicked

    private void panelCustom2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelCustom2MouseClicked
        // TODO add your handling code here:
        this.main.setVisible(true);
    }//GEN-LAST:event_panelCustom2MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ClassExtend.PanelCustom panelCustom1;
    private ClassExtend.PanelCustom panelCustom2;
    private ClassExtend.PanelCustom panelCustom3;
    // End of variables declaration//GEN-END:variables
}
