package Panel;

import ClassComponent.AccountData;
import ClassComponent.Movie;
import ClassComponent.Rating;
import ClassExtend.PanelCustom;
import ClassExtend.TranslucentPanel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author Admin
 */
public class danhgia extends javax.swing.JPanel {

    /**
     * Creates new form danhgia
     */
    private String img1 = "C:\\Java\\FinalPresent\\src\\main\\java\\Icon\\star (3).png",
                   img2 = "C:\\Java\\FinalPresent\\src\\main\\java\\Icon\\star (1).png";
    private Movie m = new Movie();
    private HomeFrame home;
    private Rating rate = new Rating();
    private AccountData account = new AccountData();
    public danhgia() {
        initComponents();
    }

    public void setHome(HomeFrame main)
    {
        this.home = main;
    }
    
    public void setMovie(Movie main)
    {
        this.m = main;
    }
    
    public void setAll3(Movie m,AccountData a)
    {
        this.m = m;
        this.account = a;
        for(int i =0;i<this.account.getRates().size();i++)
        {
            if(this.account.getRates().get(i).getMovieID() ==this.m.getID())
                jLabelScore.setText(String.valueOf(this.account.getRates().get(i).getScore()));
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new TranslucentPanel(0.2f);
        jPanel2 = new javax.swing.JPanel();
        jPanelScore = new PanelCustom(0, null, 0, "C:\\Java\\FinalPresent\\src\\main\\java\\Icon\\star (4).png", false);
        jLabelScore = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabelTitle = new javax.swing.JLabel();
        jLabelTitleMovie = new javax.swing.JLabel();
        jPanelRate = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanelStar1 = new PanelCustom(0, null, 0, "C:\\Java\\FinalPresent\\src\\main\\java\\Icon\\star (1).png", false);
        jPanelStar2 = new PanelCustom(0, null, 0, "C:\\Java\\FinalPresent\\src\\main\\java\\Icon\\star (1).png", false);
        jPanelStar3 = new PanelCustom(0, null, 0, "C:\\Java\\FinalPresent\\src\\main\\java\\Icon\\star (1).png", false);
        jPanelStar4 = new PanelCustom(0, null, 0, "C:\\Java\\FinalPresent\\src\\main\\java\\Icon\\star (1).png", false);
        jPanelStar5 = new PanelCustom(0, null, 0, "C:\\Java\\FinalPresent\\src\\main\\java\\Icon\\star (1).png", false);
        jPanelStar6 = new PanelCustom(0, null, 0, "C:\\Java\\FinalPresent\\src\\main\\java\\Icon\\star (1).png", false);
        jPanelStar7 = new PanelCustom(0, null, 0, "C:\\Java\\FinalPresent\\src\\main\\java\\Icon\\star (1).png", false);
        jPanelStar8 = new PanelCustom(0, null, 0, "C:\\Java\\FinalPresent\\src\\main\\java\\Icon\\star (1).png", false);
        jPanelStar9 = new PanelCustom(0, null, 0, "C:\\Java\\FinalPresent\\src\\main\\java\\Icon\\star (1).png", false);
        jPanelStar10 = new PanelCustom(0, null, 0, "C:\\Java\\FinalPresent\\src\\main\\java\\Icon\\star (1).png", false);
        jPanelClose = new PanelCustom(50, null, 0, "C:\\Java\\FinalPresent\\src\\main\\java\\Icon\\delete.png", false);

        setBackground(null);
        setOpaque(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setOpaque(false);

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelScore.setBackground(new java.awt.Color(0, 204, 204));
        jPanelScore.setOpaque(false);

        jLabelScore.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabelScore.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelScore.setText("?");

        javax.swing.GroupLayout jPanelScoreLayout = new javax.swing.GroupLayout(jPanelScore);
        jPanelScore.setLayout(jPanelScoreLayout);
        jPanelScoreLayout.setHorizontalGroup(
            jPanelScoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelScore, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jPanelScoreLayout.setVerticalGroup(
            jPanelScoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelScore, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        jPanel2.add(jPanelScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, -1, -1));

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));

        jLabelTitle.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(102, 255, 102));
        jLabelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitle.setText("Your Rate");

        jLabelTitleMovie.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabelTitleMovie.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitleMovie.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitleMovie.setText("Title");

        jPanelRate.setBackground(new java.awt.Color(153, 153, 153));
        jPanelRate.setEnabled(false);
        jPanelRate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelRateMouseClicked(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(0, 203, 129));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Rate");
        jLabel1.setEnabled(false);
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelRateMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelRateLayout = new javax.swing.GroupLayout(jPanelRate);
        jPanelRate.setLayout(jPanelRateLayout);
        jPanelRateLayout.setHorizontalGroup(
            jPanelRateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelRateLayout.setVerticalGroup(
            jPanelRateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanelStar1.setBackground(new java.awt.Color(204, 204, 204));
        jPanelStar1.setPreferredSize(new java.awt.Dimension(30, 30));
        jPanelStar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelStar1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelStar1Layout = new javax.swing.GroupLayout(jPanelStar1);
        jPanelStar1.setLayout(jPanelStar1Layout);
        jPanelStar1Layout.setHorizontalGroup(
            jPanelStar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanelStar1Layout.setVerticalGroup(
            jPanelStar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanelStar2.setBackground(new java.awt.Color(204, 204, 204));
        jPanelStar2.setPreferredSize(new java.awt.Dimension(30, 30));
        jPanelStar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelStar2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelStar2Layout = new javax.swing.GroupLayout(jPanelStar2);
        jPanelStar2.setLayout(jPanelStar2Layout);
        jPanelStar2Layout.setHorizontalGroup(
            jPanelStar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanelStar2Layout.setVerticalGroup(
            jPanelStar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanelStar3.setBackground(new java.awt.Color(204, 204, 204));
        jPanelStar3.setPreferredSize(new java.awt.Dimension(30, 30));
        jPanelStar3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelStar3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelStar3Layout = new javax.swing.GroupLayout(jPanelStar3);
        jPanelStar3.setLayout(jPanelStar3Layout);
        jPanelStar3Layout.setHorizontalGroup(
            jPanelStar3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanelStar3Layout.setVerticalGroup(
            jPanelStar3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanelStar4.setBackground(new java.awt.Color(204, 204, 204));
        jPanelStar4.setPreferredSize(new java.awt.Dimension(30, 30));
        jPanelStar4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelStar4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelStar4Layout = new javax.swing.GroupLayout(jPanelStar4);
        jPanelStar4.setLayout(jPanelStar4Layout);
        jPanelStar4Layout.setHorizontalGroup(
            jPanelStar4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanelStar4Layout.setVerticalGroup(
            jPanelStar4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanelStar5.setBackground(new java.awt.Color(204, 204, 204));
        jPanelStar5.setPreferredSize(new java.awt.Dimension(30, 30));
        jPanelStar5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelStar5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelStar5Layout = new javax.swing.GroupLayout(jPanelStar5);
        jPanelStar5.setLayout(jPanelStar5Layout);
        jPanelStar5Layout.setHorizontalGroup(
            jPanelStar5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanelStar5Layout.setVerticalGroup(
            jPanelStar5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanelStar6.setBackground(new java.awt.Color(204, 204, 204));
        jPanelStar6.setPreferredSize(new java.awt.Dimension(30, 30));
        jPanelStar6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelStar6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelStar6Layout = new javax.swing.GroupLayout(jPanelStar6);
        jPanelStar6.setLayout(jPanelStar6Layout);
        jPanelStar6Layout.setHorizontalGroup(
            jPanelStar6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanelStar6Layout.setVerticalGroup(
            jPanelStar6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanelStar7.setBackground(new java.awt.Color(204, 204, 204));
        jPanelStar7.setPreferredSize(new java.awt.Dimension(30, 30));
        jPanelStar7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelStar7MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelStar7Layout = new javax.swing.GroupLayout(jPanelStar7);
        jPanelStar7.setLayout(jPanelStar7Layout);
        jPanelStar7Layout.setHorizontalGroup(
            jPanelStar7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanelStar7Layout.setVerticalGroup(
            jPanelStar7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanelStar8.setBackground(new java.awt.Color(204, 204, 204));
        jPanelStar8.setPreferredSize(new java.awt.Dimension(30, 30));
        jPanelStar8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelStar8MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelStar8Layout = new javax.swing.GroupLayout(jPanelStar8);
        jPanelStar8.setLayout(jPanelStar8Layout);
        jPanelStar8Layout.setHorizontalGroup(
            jPanelStar8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanelStar8Layout.setVerticalGroup(
            jPanelStar8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanelStar9.setBackground(new java.awt.Color(204, 204, 204));
        jPanelStar9.setPreferredSize(new java.awt.Dimension(30, 30));
        jPanelStar9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelStar9MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelStar9Layout = new javax.swing.GroupLayout(jPanelStar9);
        jPanelStar9.setLayout(jPanelStar9Layout);
        jPanelStar9Layout.setHorizontalGroup(
            jPanelStar9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanelStar9Layout.setVerticalGroup(
            jPanelStar9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanelStar10.setBackground(new java.awt.Color(204, 204, 204));
        jPanelStar10.setPreferredSize(new java.awt.Dimension(30, 30));
        jPanelStar10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelStar10MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelStar10Layout = new javax.swing.GroupLayout(jPanelStar10);
        jPanelStar10.setLayout(jPanelStar10Layout);
        jPanelStar10Layout.setHorizontalGroup(
            jPanelStar10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanelStar10Layout.setVerticalGroup(
            jPanelStar10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelTitleMovie, javax.swing.GroupLayout.DEFAULT_SIZE, 574, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanelRate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jPanelStar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanelStar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanelStar3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanelStar4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanelStar5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanelStar6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanelStar7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanelStar8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanelStar9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanelStar10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(115, 115, 115))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabelTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelTitleMovie)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelStar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelStar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelStar3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelStar4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelStar5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelStar6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelStar7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelStar8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelStar9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelStar10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(jPanelRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 51, -1, -1));

        jPanelClose.setBackground(new java.awt.Color(102, 102, 102));
        jPanelClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelCloseMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelCloseLayout = new javax.swing.GroupLayout(jPanelClose);
        jPanelClose.setLayout(jPanelCloseLayout);
        jPanelCloseLayout.setHorizontalGroup(
            jPanelCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
        );
        jPanelCloseLayout.setVerticalGroup(
            jPanelCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 39, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(284, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(220, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addComponent(jPanelClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(145, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jPanelCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCloseMouseClicked
        // TODO add your handling code here:
        jLabelScore.setText("?");
        setBackground(img2,img2, img2, img2, img2, img2, img2, img2, img2, img2);
        jPanelRate.setEnabled(false);
        jLabel1.setEnabled(false);
        jPanelRate.setBackground(new java.awt.Color(153, 153, 153));
        this.setVisible(false);

    }//GEN-LAST:event_jPanelCloseMouseClicked

    private void jPanelStar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelStar1MouseClicked
        // TODO add your handling code here:
        jLabelScore.setText("1");
        setBackground(img1,img2, img2, img2, img2, img2, img2, img2, img2, img2);
        activeRate();
    }//GEN-LAST:event_jPanelStar1MouseClicked

    private void jPanelRateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelRateMouseClicked
        // TODO add your handling code here:
        if(home.getAccount().getID() <=0) 
        {
            home.callLogin();
        }
        else  
        {
            rate.setRating(account.getID(), m.getID(), Integer.parseInt(jLabelScore.getText()));
        }
            jLabelScore.setText("?");
            setBackground(img2,img2, img2, img2, img2, img2, img2, img2, img2, img2);
            jPanelRate.setEnabled(false);
            jLabel1.setEnabled(false);
            jPanelRate.setBackground(new java.awt.Color(153, 153, 153));
            this.setVisible(false);
        
    }//GEN-LAST:event_jPanelRateMouseClicked

    private void jPanelStar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelStar2MouseClicked
        // TODO add your handling code here:
        jLabelScore.setText("2");
        setBackground(img1,img1, img2, img2, img2, img2, img2, img2, img2, img2);
        activeRate();
    }//GEN-LAST:event_jPanelStar2MouseClicked

    private void jPanelStar3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelStar3MouseClicked
        // TODO add your handling code here:
        jLabelScore.setText("3");
        setBackground(img1,img1, img1, img2, img2, img2, img2, img2, img2, img2);
        activeRate();
    }//GEN-LAST:event_jPanelStar3MouseClicked

    private void jPanelStar4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelStar4MouseClicked
        // TODO add your handling code here:
        jLabelScore.setText("4");
        setBackground(img1,img1, img1, img1, img2, img2, img2, img2, img2, img2);
        activeRate();
    }//GEN-LAST:event_jPanelStar4MouseClicked

    private void jPanelStar5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelStar5MouseClicked
        // TODO add your handling code here:
        jLabelScore.setText("5");
        setBackground(img1,img1, img1, img1, img1, img2, img2, img2, img2, img2);
        activeRate();
    }//GEN-LAST:event_jPanelStar5MouseClicked

    private void jPanelStar6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelStar6MouseClicked
        // TODO add your handling code here:
        jLabelScore.setText("6");
        setBackground(img1,img1, img1, img1, img1, img1, img2, img2, img2, img2);
        activeRate();
    }//GEN-LAST:event_jPanelStar6MouseClicked

    private void jPanelStar7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelStar7MouseClicked
        // TODO add your handling code here:
        jLabelScore.setText("7");
        setBackground(img1,img1, img1, img1, img1, img1, img1, img2, img2, img2);
        activeRate();
    }//GEN-LAST:event_jPanelStar7MouseClicked

    private void jPanelStar8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelStar8MouseClicked
        // TODO add your handling code here:
        jLabelScore.setText("8");
        setBackground(img1,img1, img1, img1, img1, img1, img1, img1, img2, img2);
        activeRate();
    }//GEN-LAST:event_jPanelStar8MouseClicked

    private void jPanelStar9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelStar9MouseClicked
        // TODO add your handling code here:
        jLabelScore.setText("9");
        setBackground(img1,img1, img1, img1, img1, img1, img1, img1, img1, img2);
        activeRate();
    }//GEN-LAST:event_jPanelStar9MouseClicked

    private void jPanelStar10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelStar10MouseClicked
        // TODO add your handling code here:
        jLabelScore.setText("10");
        setBackground(img1,img1, img1, img1, img1, img1, img1, img1, img1, img1);
        activeRate();
    }//GEN-LAST:event_jPanelStar10MouseClicked

    public void setText(String txt)
    {
        jLabelTitleMovie.setText(txt);
    }
    
    public void activeRate()
    {
        jPanelRate.setEnabled(true);
        jLabel1.setEnabled(true);
        jPanelRate.setBackground(new java.awt.Color(102, 255, 102));
    }
    
    public void setBackground(String a1,String a2,String a3,String a4,String a5,String a6,String a7,String a8,String a9,String a10)
    {
        ((PanelCustom) jPanelStar1).setBackgroundImage(a1);
        ((PanelCustom) jPanelStar2).setBackgroundImage(a2);
        ((PanelCustom) jPanelStar3).setBackgroundImage(a3);
        ((PanelCustom) jPanelStar4).setBackgroundImage(a4);
        ((PanelCustom) jPanelStar5).setBackgroundImage(a5);
        ((PanelCustom) jPanelStar6).setBackgroundImage(a6);
        ((PanelCustom) jPanelStar7).setBackgroundImage(a7);
        ((PanelCustom) jPanelStar8).setBackgroundImage(a8);
        ((PanelCustom) jPanelStar9).setBackgroundImage(a9);
        ((PanelCustom) jPanelStar10).setBackgroundImage(a10);
    }
    
    public boolean checkAcc()
    {
        if(home.getAccount().getID() <=0) 
        {
            home.callLogin();
            return true;
        }
        else   
        {
            home.CallWatch(m.getUrlVideo(),m.getName());
            return false;
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelScore;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JLabel jLabelTitleMovie;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelClose;
    private javax.swing.JPanel jPanelRate;
    private javax.swing.JPanel jPanelScore;
    private javax.swing.JPanel jPanelStar1;
    private javax.swing.JPanel jPanelStar10;
    private javax.swing.JPanel jPanelStar2;
    private javax.swing.JPanel jPanelStar3;
    private javax.swing.JPanel jPanelStar4;
    private javax.swing.JPanel jPanelStar5;
    private javax.swing.JPanel jPanelStar6;
    private javax.swing.JPanel jPanelStar7;
    private javax.swing.JPanel jPanelStar8;
    private javax.swing.JPanel jPanelStar9;
    // End of variables declaration//GEN-END:variables
}
