package Panel;


import ClassComponent.AccountData;
import ClassComponent.Actor;
import ClassComponent.Director;
import ClassComponent.LoginAcc;
import ClassComponent.Movie;
import ClassExtend.GradientPanel;
import ClassExtend.TranslucentPanel;
import ClassExtend.ImageBackGround;
import ClassExtend.PanelCustom;
import ClassExtend.RoundedPanel;
import Interface.LoginListener;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import java.awt.Point;
import java.awt.Shape;
import java.awt.geom.RoundRectangle2D;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JPanel;
import ClassExtend.CustomScrollBarUI;
import java.awt.Component;
import java.util.HashMap;
import java.util.Map;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Admin
 */

public class HomeFrame extends JFrame implements LoginListener{

    /**
     * Creates new form HomeFrame
     */
    private static boolean isFullScreen = false;
    private Point initialClick;
    private boolean resizing; 
    private int currentX, currentY, currentWidth, currentHeight;
    private final int RESIZE_MARGIN = 10;
    private static GraphicsDevice device = GraphicsEnvironment.getLocalGraphicsEnvironment().getScreenDevices()[0];
    private AccountData account = new AccountData();
    private LoginAcc log = new LoginAcc();
    public static WatchPanel watchpanel1 = null ;
    private Movie movie = new Movie();
    private Actor actor = new Actor();
    private Director director = new Director();
    
    public HomeFrame() {
        //super(Color.RED, 5, 20);
        initComponents();
        Shape shape = new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 20, 20);
        setShape(shape);

    }

    public void setAccount(AccountData account) {
        this.account = account;
    }

    public AccountData getAccount() {
        return account;
    }

    

    public JPanel getBodyPanel() {
        //return BodyPanel;
        return null;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBg = new javax.swing.JPanel();
        jPanelHeadMenu = new javax.swing.JPanel();
        ExtBtn = new PanelCustom(0,Color.BLACK,0,"C:\\Java\\FinalPresent\\src\\main\\java\\Icon\\x-button(2).png",true);
        FulScrBtn = new PanelCustom(0,Color.BLACK,0,"C:\\Java\\FinalPresent\\src\\main\\java\\Icon\\square.png",true);
        MinBtn = new PanelCustom(0,Color.BLACK,0,"C:\\Java\\FinalPresent\\src\\main\\java\\Icon\\minus-sign.png",true);
        Header = new javax.swing.JPanel();
        Homebtn =  new PanelCustom(20,Color.BLACK,2,"C:\\Java\\FinalPresent\\src\\main\\java\\Icon\\Logo1.png",false);
        jPanelSearchBar = new RoundedPanel(20,new java.awt.Color(255, 255, 255),2);
        jPanelSearchIcon = new ImageBackGround("C:\\Java\\FinalPresent\\src\\main\\java\\Icon\\search.png");
        jTextFieldSearch = new javax.swing.JTextField();
        jPanelList = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanelWatchlistIcon = new ImageBackGround("C:\\Java\\FinalPresent\\src\\main\\java\\Icon\\bookmarkWhite.png");
        jLabelWatchlist = new javax.swing.JLabel();
        jPanelAcc = new javax.swing.JPanel();
        jPanelSignIn = new javax.swing.JPanel();
        jLabelSignIn = new javax.swing.JLabel();
        accountUser = new Panel.Account();
        accountAdmin1 = new Panel.AccountAdmin();
        jPanelMain = new javax.swing.JPanel();
        jPanelDiemDanh = new TranslucentPanel(0.3f);
        diemdanh1 = new Panel.diemdanh();
        jPanelClose = new PanelCustom(50, null, 0, "C:\\Java\\FinalPresent\\src\\main\\java\\Icon\\delete.png", false);
        danhgia2 = new Panel.danhgia();
        jScrollPaneBody = new javax.swing.JScrollPane();
        BodyPanel = new javax.swing.JPanel();
        homePanelNLogin1 = new Panel.HomePanelNLogin();
        jPanelDangNhap = new PanelCustom(0, null, 0, "C:\\Java\\FinalPresent\\src\\main\\java\\Icon\\movie-poster-background-q1zm830g0hfww2lk.jpg",true);
        jPanel2 = new TranslucentPanel(0.2f);
        panelLogin1 = new Panel.PanelLogin();
        jPanelLib3 = new javax.swing.JPanel();
        phim_yeuthich1 = new Panel.phim_yeuthich();
        jLabel1 = new javax.swing.JLabel();
        watchPanel1 = new Panel.WatchPanel();
        jPanelNotifice = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        diemdanh2 = new Panel.diemdanh();
        thongbao1 = new Panel.thongbao();
        pnlThongtin2 = new Panel.pnlThongtin();
        thongtin1 = new Panel.thongtin();
        jPanel1 = new javax.swing.JPanel();
        timkiem1 = new Panel.Timkiem();
        quanly_nd1 = new Panel.quanly_nd();
        jPanelUser = new javax.swing.JPanel();
        chọn_chucnang_nd1 = new Panel.chọn_chucnang_nd();
        jPanelAdmin = new javax.swing.JPanel();
        chon_chucnang_admin1 = new Panel.chon_chucnang_admin();
        quanly_nd2 = new Panel.quanly_nd();
        jPanelChangePass = new javax.swing.JPanel();
        doimatkhau1 = new Panel.doimatkhau();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(20, 20));
        setMinimumSize(new java.awt.Dimension(1320, 360));
        setUndecorated(true);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        jPanelBg.setBackground(new java.awt.Color(0, 0, 0));
        jPanelBg.setPreferredSize(new java.awt.Dimension(1545, 720));

        jPanelHeadMenu.setBackground(new java.awt.Color(0, 0, 0));
        jPanelHeadMenu.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanelHeadMenu.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanelHeadMenuMouseDragged(evt);
            }
        });
        jPanelHeadMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelHeadMenuMousePressed(evt);
            }
        });

        ExtBtn.setBackground(new java.awt.Color(0, 0, 0));
        ExtBtn.setPreferredSize(new java.awt.Dimension(28, 28));
        ExtBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExtBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ExtBtn1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ExtBtnMouseExited(evt);
            }
        });

        javax.swing.GroupLayout ExtBtnLayout = new javax.swing.GroupLayout(ExtBtn);
        ExtBtn.setLayout(ExtBtnLayout);
        ExtBtnLayout.setHorizontalGroup(
            ExtBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );
        ExtBtnLayout.setVerticalGroup(
            ExtBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        FulScrBtn.setBackground(new java.awt.Color(0, 0, 0));
        FulScrBtn.setPreferredSize(new java.awt.Dimension(28, 28));
        FulScrBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FulScrBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                FulScrBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                FulScrBtnMouseExited(evt);
            }
        });

        javax.swing.GroupLayout FulScrBtnLayout = new javax.swing.GroupLayout(FulScrBtn);
        FulScrBtn.setLayout(FulScrBtnLayout);
        FulScrBtnLayout.setHorizontalGroup(
            FulScrBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );
        FulScrBtnLayout.setVerticalGroup(
            FulScrBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        MinBtn.setBackground(new java.awt.Color(0, 0, 0));
        MinBtn.setPreferredSize(new java.awt.Dimension(28, 28));
        MinBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MinBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MinBtnMouseExited(evt);
            }
        });

        javax.swing.GroupLayout MinBtnLayout = new javax.swing.GroupLayout(MinBtn);
        MinBtn.setLayout(MinBtnLayout);
        MinBtnLayout.setHorizontalGroup(
            MinBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );
        MinBtnLayout.setVerticalGroup(
            MinBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelHeadMenuLayout = new javax.swing.GroupLayout(jPanelHeadMenu);
        jPanelHeadMenu.setLayout(jPanelHeadMenuLayout);
        jPanelHeadMenuLayout.setHorizontalGroup(
            jPanelHeadMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHeadMenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(MinBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FulScrBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ExtBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelHeadMenuLayout.setVerticalGroup(
            jPanelHeadMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MinBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(FulScrBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ExtBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Header.setBackground(new java.awt.Color(0, 0, 0));
        Header.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Header.setPreferredSize(new java.awt.Dimension(1320, 60));

        Homebtn.setBackground(new java.awt.Color(105, 240, 28));
        Homebtn.setPreferredSize(new java.awt.Dimension(60, 30));
        Homebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomebtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout HomebtnLayout = new javax.swing.GroupLayout(Homebtn);
        Homebtn.setLayout(HomebtnLayout);
        HomebtnLayout.setHorizontalGroup(
            HomebtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 59, Short.MAX_VALUE)
        );
        HomebtnLayout.setVerticalGroup(
            HomebtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanelSearchBar.setBackground(new java.awt.Color(255, 255, 255));
        jPanelSearchBar.setPreferredSize(new java.awt.Dimension(636, 30));

        jPanelSearchIcon.setBackground(new java.awt.Color(255, 255, 255));
        jPanelSearchIcon.setPreferredSize(new java.awt.Dimension(20, 20));
        jPanelSearchIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelSearchIconMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelSearchIconLayout = new javax.swing.GroupLayout(jPanelSearchIcon);
        jPanelSearchIcon.setLayout(jPanelSearchIconLayout);
        jPanelSearchIconLayout.setHorizontalGroup(
            jPanelSearchIconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanelSearchIconLayout.setVerticalGroup(
            jPanelSearchIconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jTextFieldSearch.setBorder(null);
        jTextFieldSearch.setHighlighter(null);
        jTextFieldSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelSearchBarLayout = new javax.swing.GroupLayout(jPanelSearchBar);
        jPanelSearchBar.setLayout(jPanelSearchBarLayout);
        jPanelSearchBarLayout.setHorizontalGroup(
            jPanelSearchBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSearchBarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextFieldSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 712, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanelSearchIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelSearchBarLayout.setVerticalGroup(
            jPanelSearchBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSearchBarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelSearchBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelSearchIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelList.setBackground(new java.awt.Color(0, 0, 0));
        jPanelList.setPreferredSize(new java.awt.Dimension(196, 30));
        jPanelList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelListMouseClicked(evt);
            }
        });
        jPanelList.setLayout(new java.awt.CardLayout());

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
        });

        jPanelWatchlistIcon.setBackground(new java.awt.Color(0, 0, 0));
        jPanelWatchlistIcon.setPreferredSize(new java.awt.Dimension(30, 30));
        jPanelWatchlistIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelWatchlistIconLayout = new javax.swing.GroupLayout(jPanelWatchlistIcon);
        jPanelWatchlistIcon.setLayout(jPanelWatchlistIconLayout);
        jPanelWatchlistIconLayout.setHorizontalGroup(
            jPanelWatchlistIconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
        );
        jPanelWatchlistIconLayout.setVerticalGroup(
            jPanelWatchlistIconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
        );

        jLabelWatchlist.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabelWatchlist.setForeground(new java.awt.Color(255, 255, 255));
        jLabelWatchlist.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelWatchlist.setText("Watchlist");
        jLabelWatchlist.setPreferredSize(new java.awt.Dimension(106, 30));
        jLabelWatchlist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jLabelWatchlist, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addComponent(jPanelWatchlistIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 119, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelWatchlist, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelWatchlistIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
        );

        jPanelList.add(jPanel4, "Watchlist");

        jPanelAcc.setBackground(new java.awt.Color(0, 0, 0));
        jPanelAcc.setPreferredSize(new java.awt.Dimension(100, 44));
        jPanelAcc.setLayout(new java.awt.CardLayout());

        jPanelSignIn.setBackground(new java.awt.Color(0, 0, 0));
        jPanelSignIn.setPreferredSize(new java.awt.Dimension(100, 46));
        jPanelSignIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelSignInMouseClicked(evt);
            }
        });

        jLabelSignIn.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabelSignIn.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSignIn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSignIn.setText("Sign in");
        jLabelSignIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelSignInMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelSignInLayout = new javax.swing.GroupLayout(jPanelSignIn);
        jPanelSignIn.setLayout(jPanelSignInLayout);
        jPanelSignInLayout.setHorizontalGroup(
            jPanelSignInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelSignIn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
        );
        jPanelSignInLayout.setVerticalGroup(
            jPanelSignInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelSignIn, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        jPanelAcc.add(jPanelSignIn, "SignIn");

        accountUser.setBody(BodyPanel);
        accountUser.setMain(jPanelDiemDanh);
        accountUser.setAcc(this.account);
        accountUser.setHome(this);
        jPanelAcc.add(accountUser, "LogIn");

        accountAdmin1.setBody(this);
        accountAdmin1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                accountAdmin1MouseClicked(evt);
            }
        });
        jPanelAcc.add(accountAdmin1, "Admin");

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Homebtn, 59, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jPanelSearchBar, javax.swing.GroupLayout.PREFERRED_SIZE, 762, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(jPanelList, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelAcc, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Homebtn, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(jPanelAcc, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanelList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelSearchBar, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanelMain.setBackground(new java.awt.Color(0, 0, 0));
        jPanelMain.setLayout(new javax.swing.OverlayLayout(jPanelMain));

        jPanelDiemDanh.setBackground(new java.awt.Color(0, 0, 0));
        jPanelDiemDanh.setOpaque(false);
        jPanelDiemDanh.setVisible(false);

        jPanelClose.setBackground(new java.awt.Color(102, 102, 102));
        jPanelClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelCloseMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelCloseLayout = new javax.swing.GroupLayout(jPanelClose);
        jPanelClose.setLayout(jPanelCloseLayout);
        jPanelCloseLayout.setHorizontalGroup(
            jPanelCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
        );
        jPanelCloseLayout.setVerticalGroup(
            jPanelCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 39, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelDiemDanhLayout = new javax.swing.GroupLayout(jPanelDiemDanh);
        jPanelDiemDanh.setLayout(jPanelDiemDanhLayout);
        jPanelDiemDanhLayout.setHorizontalGroup(
            jPanelDiemDanhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDiemDanhLayout.createSequentialGroup()
                .addContainerGap(560, Short.MAX_VALUE)
                .addGroup(jPanelDiemDanhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDiemDanhLayout.createSequentialGroup()
                        .addComponent(jPanelClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(405, 405, 405))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDiemDanhLayout.createSequentialGroup()
                        .addComponent(diemdanh1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(463, Short.MAX_VALUE))))
        );
        jPanelDiemDanhLayout.setVerticalGroup(
            jPanelDiemDanhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDiemDanhLayout.createSequentialGroup()
                .addContainerGap(230, Short.MAX_VALUE)
                .addComponent(jPanelClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(diemdanh1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(124, Short.MAX_VALUE))
        );

        jPanelMain.add(jPanelDiemDanh);

        danhgia2.setVisible(false);
        jPanelMain.add(danhgia2);

        jScrollPaneBody.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPaneBody.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPaneBody.getVerticalScrollBar().setUI(new CustomScrollBarUI());

        BodyPanel.setBackground(new java.awt.Color(0, 0, 0));
        BodyPanel.setMinimumSize(new java.awt.Dimension(1293, 760));
        BodyPanel.setPreferredSize(homePanelNLogin1.getPreferredSize());
        BodyPanel.setLayout(new java.awt.CardLayout());

        homePanelNLogin1.setPanelHot(this.BodyPanel);
        homePanelNLogin1.setFrameHot(this);
        homePanelNLogin1.setListMovie(movie.getMovie());
        homePanelNLogin1.setDanhgia(danhgia2);
        homePanelNLogin1.setThongtin(thongtin1);
        BodyPanel.add(homePanelNLogin1, "Home");

        jPanelDangNhap.setBackground(new java.awt.Color(255, 255, 255));
        jPanelDangNhap.setLayout(new java.awt.CardLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        panelLogin1.setBody(BodyPanel);
        panelLogin1.setAccLogin(jPanelAcc);
        panelLogin1.setHome(this);
        panelLogin1.setListener(this);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelLogin1, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(panelLogin1, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelDangNhap.add(jPanel2, "card2");

        BodyPanel.add(jPanelDangNhap, "Login");

        jPanelLib3.setBackground(new java.awt.Color(0, 0, 0));

        phim_yeuthich1.setHome(this);
        phim_yeuthich1.setMaximumSize(new java.awt.Dimension(1200, 32767));
        phim_yeuthich1.setLayout(new java.awt.FlowLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PHIM YÊU THÍCH");

        javax.swing.GroupLayout jPanelLib3Layout = new javax.swing.GroupLayout(jPanelLib3);
        jPanelLib3.setLayout(jPanelLib3Layout);
        jPanelLib3Layout.setHorizontalGroup(
            jPanelLib3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLib3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelLib3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(phim_yeuthich1, javax.swing.GroupLayout.DEFAULT_SIZE, 1100, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelLib3Layout.setVerticalGroup(
            jPanelLib3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLib3Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(phim_yeuthich1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        BodyPanel.add(jPanelLib3, "Lib");
        BodyPanel.add(watchPanel1, "Watch");

        jPanelNotifice.setLayout(new java.awt.CardLayout());

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(diemdanh2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addComponent(diemdanh2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelNotifice.add(jPanel3, "card4");
        jPanelNotifice.add(thongbao1, "card2");

        BodyPanel.add(jPanelNotifice, "card8");
        BodyPanel.add(pnlThongtin2, "Account");
        BodyPanel.add(thongtin1, "Thongtin");

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(timkiem1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(timkiem1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        BodyPanel.add(jPanel1, "Search");
        BodyPanel.add(quanly_nd1, "card12");

        jPanelUser.setBackground(new java.awt.Color(0, 0, 0));

        chọn_chucnang_nd1.setHome(this);
        chọn_chucnang_nd1.setMain(jPanelDiemDanh);

        javax.swing.GroupLayout jPanelUserLayout = new javax.swing.GroupLayout(jPanelUser);
        jPanelUser.setLayout(jPanelUserLayout);
        jPanelUserLayout.setHorizontalGroup(
            jPanelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1456, Short.MAX_VALUE)
            .addGroup(jPanelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelUserLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chọn_chucnang_nd1, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanelUserLayout.setVerticalGroup(
            jPanelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 760, Short.MAX_VALUE)
            .addGroup(jPanelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(chọn_chucnang_nd1, javax.swing.GroupLayout.DEFAULT_SIZE, 760, Short.MAX_VALUE))
        );

        BodyPanel.add(jPanelUser, "user");

        jPanelAdmin.setBackground(new java.awt.Color(0, 0, 0));

        chon_chucnang_admin1.setHome(this);

        javax.swing.GroupLayout jPanelAdminLayout = new javax.swing.GroupLayout(jPanelAdmin);
        jPanelAdmin.setLayout(jPanelAdminLayout);
        jPanelAdminLayout.setHorizontalGroup(
            jPanelAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAdminLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(chon_chucnang_admin1, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelAdminLayout.setVerticalGroup(
            jPanelAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(chon_chucnang_admin1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 760, Short.MAX_VALUE)
        );

        BodyPanel.add(jPanelAdmin, "admin");
        BodyPanel.add(quanly_nd2, "AccManager");

        jPanelChangePass.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanelChangePassLayout = new javax.swing.GroupLayout(jPanelChangePass);
        jPanelChangePass.setLayout(jPanelChangePassLayout);
        jPanelChangePassLayout.setHorizontalGroup(
            jPanelChangePassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelChangePassLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(doimatkhau1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelChangePassLayout.setVerticalGroup(
            jPanelChangePassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelChangePassLayout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addComponent(doimatkhau1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        BodyPanel.add(jPanelChangePass, "ChangePass");

        jScrollPaneBody.setViewportView(BodyPanel);

        jPanelMain.add(jScrollPaneBody);

        javax.swing.GroupLayout jPanelBgLayout = new javax.swing.GroupLayout(jPanelBg);
        jPanelBg.setLayout(jPanelBgLayout);
        jPanelBgLayout.setHorizontalGroup(
            jPanelBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelHeadMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Header, javax.swing.GroupLayout.DEFAULT_SIZE, 1458, Short.MAX_VALUE)
            .addComponent(jPanelMain, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelBgLayout.setVerticalGroup(
            jPanelBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBgLayout.createSequentialGroup()
                .addComponent(jPanelHeadMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Header, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, 674, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBg, javax.swing.GroupLayout.DEFAULT_SIZE, 1458, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBg, javax.swing.GroupLayout.DEFAULT_SIZE, 764, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExtBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExtBtnMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ExtBtnMouseClicked

    private void jPanelHeadMenuMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelHeadMenuMouseDragged
        // TODO add your handling code here:
        // Lấy vị trí hiện tại của cửa sổ
        int thisX = getLocation().x;
        int thisY = getLocation().y;
        
        // Tính toán vị trí mới của cửa sổ 
        int xMoved = evt.getX() - initialClick.x; 
        int yMoved = evt.getY() - initialClick.y; 
        int X = thisX + xMoved; 
        int Y = thisY + yMoved;
        // Di chuyển cửa sổ đến vị trí mới
        setLocation(X, Y);
    }//GEN-LAST:event_jPanelHeadMenuMouseDragged

    private void jPanelHeadMenuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelHeadMenuMousePressed
        // TODO add your handling code here:
        initialClick = evt.getPoint(); 
        getComponentAt(initialClick);
    }//GEN-LAST:event_jPanelHeadMenuMousePressed

    private void ExtBtn1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExtBtn1MouseEntered
        // TODO add your handling code here:
        ExtBtn.setBackground(Color.red);
    }//GEN-LAST:event_ExtBtn1MouseEntered

    private void ExtBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExtBtnMouseExited
        // TODO add your handling code here:
        ExtBtn.setBackground(Color.BLACK);
    }//GEN-LAST:event_ExtBtnMouseExited

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
        initialClick = evt.getPoint();
        currentX = getX(); 
        currentY = getY(); 
        currentWidth = getWidth(); 
        currentHeight = getHeight(); 
        // Kiểm tra xem có phải resizing hay không 
        if (initialClick.x >= getWidth() - RESIZE_MARGIN || initialClick.y >= getHeight() - RESIZE_MARGIN) 
        { 
            resizing = true; 
        } 
        else 
        { 
            resizing = false; 
        }
    }//GEN-LAST:event_formMousePressed

    private void FulScrBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FulScrBtnMouseClicked
        // TODO add your handling code here:
        if (!isFullScreen) 
        { 
            //dispose();
            device.setFullScreenWindow(this); // Thoát khỏi chế độ toàn màn hình 
            setVisible(true); // Đảm bảo frame được hiển thị trở lại
            if(FulScrBtn instanceof PanelCustom)
            {
                ((PanelCustom) FulScrBtn).setBackgroundImage("C:\\Java\\FinalPresent\\src\\main\\java\\Icon\\square(1).png");
                FulScrBtn.setBackground(Color.black);
            }
        }
        else 
        { 
            device.setFullScreenWindow(null); // Chuyển sang chế độ toàn màn hình 
            //dispose();
            setVisible(true);
            if(FulScrBtn instanceof PanelCustom)
            {
                ((PanelCustom) FulScrBtn).setBackgroundImage("C:\\Java\\FinalPresent\\src\\main\\java\\Icon\\square.png");
                FulScrBtn.setBackground(Color.black);
            }
        } 
        isFullScreen = !isFullScreen; // Đổi trạng thái toàn màn hình 

    }//GEN-LAST:event_FulScrBtnMouseClicked

    private void FulScrBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FulScrBtnMouseEntered
        // TODO add your handling code here:
        FulScrBtn.setBackground(Color.gray);
    }//GEN-LAST:event_FulScrBtnMouseEntered

    private void FulScrBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FulScrBtnMouseExited
        // TODO add your handling code here:
        FulScrBtn.setBackground(Color.black);
    }//GEN-LAST:event_FulScrBtnMouseExited

    private void MinBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinBtnMouseEntered
        // TODO add your handling code here:
        MinBtn.setBackground(Color.gray);
    }//GEN-LAST:event_MinBtnMouseEntered

    private void MinBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinBtnMouseExited
        // TODO add your handling code here:
        MinBtn.setBackground(Color.black);
    }//GEN-LAST:event_MinBtnMouseExited

    private void MinBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinBtnMouseClicked
        // TODO add your handling code here:
        setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_MinBtnMouseClicked

    private void jPanelSignInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelSignInMouseClicked
        // TODO add your handling code here:
        BodyPanel.setPreferredSize(watchPanel1.getPreferredSize());
        ChangePanel("Login");
    }//GEN-LAST:event_jPanelSignInMouseClicked

    private void jPanelListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelListMouseClicked
        // TODO add your handling code here:
        callWatchList();
    }//GEN-LAST:event_jPanelListMouseClicked

    public void callWatchList()
    {
        if(account.getID()<= 0)
        {
            
            BodyPanel.setPreferredSize(jPanel2.getPreferredSize());
            ChangePanel("Login");
        }
        else
        {
            BodyPanel.setPreferredSize(watchPanel1.getPreferredSize());
            ChangePanel("Lib");
        }
    }
    
    private void jTextFieldSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSearchActionPerformed
        // TODO add your handling code here:
        setSearch();
    }//GEN-LAST:event_jTextFieldSearchActionPerformed

    private void jPanelSearchIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelSearchIconMouseClicked
        // TODO add your handling code here:
        setSearch();
    }//GEN-LAST:event_jPanelSearchIconMouseClicked

    public void setSearch()
    {
        timkiem1.refresh();
        
        List<Movie> lstM = movie.SearchMovieTitle(jTextFieldSearch.getText());
        for(int i=0;i<lstM.size();i++)
        {
            timkiem1.setM(lstM.get(i));
        }
        
        List<Actor> lstA = actor.SearchActorOnly(jTextFieldSearch.getText());
        for(int i=0;i<lstA.size();i++)
        {
            timkiem1.setA(lstA.get(i));
        }
        
        List<Director> lstD = director.getDirectorByName(jTextFieldSearch.getText());
        for(int i=0;i<lstD.size();i++)
        {
            timkiem1.setD(lstD.get(i));
        }
        BodyPanel.setPreferredSize(timkiem1.getPreferredSize());
        ChangePanel("Search");
    }
    
    private void HomebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomebtnMouseClicked
        // TODO add your handling code here:
        BodyPanel.setPreferredSize(homePanelNLogin1.getPreferredSize());
        ChangePanel("Home");
    }//GEN-LAST:event_HomebtnMouseClicked

    private void jLabelSignInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSignInMouseClicked
        // TODO add your handling code here:
        callLogin();
    }//GEN-LAST:event_jLabelSignInMouseClicked

    public void callLogin()
    {
        BodyPanel.setPreferredSize(jPanel2.getPreferredSize());
        ChangePanel("Login");
    }
    
    private void jPanelCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCloseMouseClicked
        // TODO add your handling code here:
        jPanelDiemDanh.setVisible(false);
    }//GEN-LAST:event_jPanelCloseMouseClicked

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
        // TODO add your handling code here:
        callWatchList();
    }//GEN-LAST:event_jPanel4MouseClicked

    private void accountAdmin1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountAdmin1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_accountAdmin1MouseClicked

    public void callMain()
    {
        CardLayout card = (CardLayout) BodyPanel.getLayout();
        BodyPanel.setPreferredSize(homePanelNLogin1.getPreferredSize());
        card.show(BodyPanel, "Home");
        if("admin".equals(account.getRole()))
        {
            CardLayout card1 = (CardLayout) jPanelAcc.getLayout();
            card1.show(jPanelAcc, "Admin");
        }
        else if("user".equals(account.getRole()))
        {
            CardLayout card1 = (CardLayout) jPanelAcc.getLayout();
            card1.show(jPanelAcc, "LogIn");
        }
        else 
        {
            CardLayout card1 = (CardLayout) jPanelAcc.getLayout();
            card1.show(jPanelAcc, "SignIn");
        }
    }
    
    public void CallWatch(String pURl,String name)
    {
        //BodyPanel.setPreferredSize(watchPanel1.getPreferredSize());
        watchPanel1.setTitle(name);
        watchPanel1.setURL(pURl);
        ChangePanel("Watch");
    }
    
    public void ChangePanel(String name)
    {
        
        CardLayout cardLayout = (CardLayout) BodyPanel.getLayout();
        if(watchPanel1.isVisible()) watchPanel1.stopMedia();
        cardLayout.show(BodyPanel, name);
        /**/
    }    
    
    public void ChangeWatchPanel()
    {
        watchPanel1.setURL("C:\\Java\\FinalPresent\\src\\main\\java\\Video\\BGbh9DEB-NJEpRIs.mp4");
        ChangePanel("Watch");
        
    }
    
    private void CallWatchPanel(String URL)
    {
        try
        {
            if (watchpanel1 != null) 
            {
                removePanel(watchpanel1);
            }
            watchpanel1 = new WatchPanel();
            watchpanel1.setURL(URL);
            ChangePanel("Watch");
        }catch(Exception ex)
        {
            System.out.println("CallWatchPanel Error: "+ ex.getMessage());
        }
    }
    
    private void removePanel(JPanel panel) {
        BodyPanel.remove(panel);
        BodyPanel.revalidate();
        BodyPanel.repaint();
    }
    
    public void callAdminFunction()
    {

        BodyPanel.setPreferredSize(chon_chucnang_admin1.getPreferredSize());
        ChangePanel("admin");
    }
    
    public void callUserFunction()
    {
        BodyPanel.setPreferredSize(chọn_chucnang_nd1.getPreferredSize());
        ChangePanel("user");
    }
    
    public void callUserFunctionDoimk()
    {
        BodyPanel.setPreferredSize(jPanelChangePass.getPreferredSize());
        ChangePanel("ChangePass");
    }
    
    public void callAdminFunctionAccMng()
    {
        BodyPanel.setPreferredSize(quanly_nd2.getPreferredSize());
        ChangePanel("AccManager");
    }    
    
    public void Logout()
    {
        this.account = new AccountData();
        callMain();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BodyPanel;
    private javax.swing.JPanel ExtBtn;
    private javax.swing.JPanel FulScrBtn;
    private javax.swing.JPanel Header;
    private javax.swing.JPanel Homebtn;
    private javax.swing.JPanel MinBtn;
    private Panel.AccountAdmin accountAdmin1;
    private Panel.Account accountUser;
    private Panel.chon_chucnang_admin chon_chucnang_admin1;
    private Panel.chọn_chucnang_nd chọn_chucnang_nd1;
    private Panel.danhgia danhgia2;
    private Panel.diemdanh diemdanh1;
    private Panel.diemdanh diemdanh2;
    private Panel.doimatkhau doimatkhau1;
    public Panel.HomePanelNLogin homePanelNLogin1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelSignIn;
    private javax.swing.JLabel jLabelWatchlist;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelAcc;
    private javax.swing.JPanel jPanelAdmin;
    private javax.swing.JPanel jPanelBg;
    private javax.swing.JPanel jPanelChangePass;
    private javax.swing.JPanel jPanelClose;
    private javax.swing.JPanel jPanelDangNhap;
    private javax.swing.JPanel jPanelDiemDanh;
    private javax.swing.JPanel jPanelHeadMenu;
    private javax.swing.JPanel jPanelLib3;
    private javax.swing.JPanel jPanelList;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JPanel jPanelNotifice;
    private javax.swing.JPanel jPanelSearchBar;
    private javax.swing.JPanel jPanelSearchIcon;
    private javax.swing.JPanel jPanelSignIn;
    private javax.swing.JPanel jPanelUser;
    private javax.swing.JPanel jPanelWatchlistIcon;
    private javax.swing.JScrollPane jScrollPaneBody;
    private javax.swing.JTextField jTextFieldSearch;
    private Panel.PanelLogin panelLogin1;
    public Panel.phim_yeuthich phim_yeuthich1;
    private Panel.pnlThongtin pnlThongtin2;
    private Panel.quanly_nd quanly_nd1;
    private Panel.quanly_nd quanly_nd2;
    private Panel.thongbao thongbao1;
    private Panel.thongtin thongtin1;
    private Panel.Timkiem timkiem1;
    public Panel.WatchPanel watchPanel1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void onLoginSuccess(AccountData account) {
         // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        this.account = account;
        phim_yeuthich1.loadList(thongtin1);
        pnlThongtin2.chgpnlThongtin(this.account);
    }
}
