/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Panel;

import ClassComponent.Movie;
import ClassExtend.CustomButton;
import ClassExtend.ImageBackGround;
import java.awt.Color;
import java.util.List;
import javax.swing.JPanel;
import ClassExtend.PanelCustom;

/**
 *
 * @author Admin
 */
public class HomePanelNLogin extends javax.swing.JPanel {

    private static JPanel panel;
    //private List<Movie> movies = new ArrayList<>();
    /**
     * Creates new form HomePanel
     */

    public HomePanelNLogin() {
        initComponents();
    }
    
    public void setThongtin(thongtin tt)
    {
        hotFilmPanel1.setPanelThongtin(tt);
        hotFilmPanel2.setPanelThongtin(tt);
        hotFilmPanel3.setPanelThongtin(tt);
    }
    
    public void setListMovie(List<Movie> movies)
    {
        hotFilmPanel1.setPanelxemtruoc1Movie(movies);
        hotFilmPanel2.setPanelxemtruoc1Movie(movies);
        hotFilmPanel3.setPanelxemtruoc1Movie(movies);
    }

    public void setPanelHot(JPanel body) {
        hotFilmPanel1.setPanelxemtrc(body);
        hotFilmPanel2.setPanelxemtrc(body);   
        hotFilmPanel3.setPanelxemtrc(body);   
    }

    public void setFrameHot(HomeFrame Home) {
        hotFilmPanel1.setFramexemtrc(Home);
        hotFilmPanel2.setFramexemtrc(Home);   
        hotFilmPanel3.setFramexemtrc(Home);   
    }
    
    public JPanel getPanel() {
        
        return panel;
    }

    public void setDanhgia(danhgia dg)
    {
        hotFilmPanel1.setDanhgia(dg);
        hotFilmPanel2.setDanhgia(dg);  
        hotFilmPanel3.setDanhgia(dg);
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFilmHot = new javax.swing.JPanel();
        jPanelFilmHot1 = new javax.swing.JPanel();
        jButtonPrev = new CustomButton(0.7f, Color.WHITE, 10, 1.0f);
        jButtonNext = new CustomButton(0.7f, Color.WHITE, 10, 1.0f);
        jPanel1 = new PanelCustom(20,null,0,"C:\\Java\\FinalPresent\\src\\main\\java\\Icon\\AAAABZzAZtTJiXy0rHGo1vmr9mxXVXMSJ24BGik9hhbt-emRHoSq-lhGzuFNhvxIB5Y7AQSl6-BMzT9ZuFuzNBs02ZEybWiJOvjc1Ruy.jpg",false);
        jPanelFilmHot2 = new ImageBackGround("C:\\Java\\FinalPresent\\src\\main\\java\\Icon\\harry_potter_wallpaper_digital_design____11_by_sefabaris713_de5yl8r-fullview.jpg");
        jPanelFilmHot3 = new ImageBackGround("C:\\Java\\FinalPresent\\src\\main\\java\\Icon\\MV5BOWIyZTdkYjktZjkxMC00YjRlLWJmMjItNjg2M2IyYzJjMTY2XkEyXkFqcGdeQWRvb2xpbmhk._V1_QL75_UY281_CR0,0,500,281_.jpg");
        jPanelFilmHot4 = new ImageBackGround("C:\\Java\\FinalPresent\\src\\main\\java\\Icon\\17c44040a61b11efb55e093e10ade9bd.png");
        hotFilmPanel1 = new Panel.HotFilmPanel();
        hotFilmPanel2 = new Panel.HotFilmPanel();
        hotFilmPanel3 = new Panel.HotFilmPanel();

        setBackground(new java.awt.Color(0, 0, 0));

        jPanelFilmHot.setBackground(new java.awt.Color(0, 0, 0));
        jPanelFilmHot.setPreferredSize(new java.awt.Dimension(1290, 300));

        jPanelFilmHot1.setBackground(new java.awt.Color(102, 255, 102));
        jPanelFilmHot1.setOpaque(false);
        jPanelFilmHot1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonPrev.setFont(new java.awt.Font("Rockwell Condensed", 1, 36)); // NOI18N
        jButtonPrev.setText("<<");
        jButtonPrev.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jButtonPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrevActionPerformed(evt);
            }
        });
        jPanelFilmHot1.add(jButtonPrev, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 60, 40));

        jButtonNext.setFont(new java.awt.Font("Rockwell Condensed", 1, 36)); // NOI18N
        jButtonNext.setText(">>");
        jButtonNext.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jButtonNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNextActionPerformed(evt);
            }
        });
        jPanelFilmHot1.add(jButtonNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 100, 60, 40));

        jPanel1.setOpaque(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 760, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
        );

        jPanelFilmHot1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 330));

        jPanelFilmHot2.setBackground(new java.awt.Color(204, 255, 204));

        javax.swing.GroupLayout jPanelFilmHot2Layout = new javax.swing.GroupLayout(jPanelFilmHot2);
        jPanelFilmHot2.setLayout(jPanelFilmHot2Layout);
        jPanelFilmHot2Layout.setHorizontalGroup(
            jPanelFilmHot2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 401, Short.MAX_VALUE)
        );
        jPanelFilmHot2Layout.setVerticalGroup(
            jPanelFilmHot2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanelFilmHot3.setBackground(new java.awt.Color(204, 255, 204));
        jPanelFilmHot3.setPreferredSize(new java.awt.Dimension(401, 103));

        javax.swing.GroupLayout jPanelFilmHot3Layout = new javax.swing.GroupLayout(jPanelFilmHot3);
        jPanelFilmHot3.setLayout(jPanelFilmHot3Layout);
        jPanelFilmHot3Layout.setHorizontalGroup(
            jPanelFilmHot3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 401, Short.MAX_VALUE)
        );
        jPanelFilmHot3Layout.setVerticalGroup(
            jPanelFilmHot3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 103, Short.MAX_VALUE)
        );

        jPanelFilmHot4.setBackground(new java.awt.Color(204, 255, 204));
        jPanelFilmHot4.setPreferredSize(new java.awt.Dimension(401, 103));

        javax.swing.GroupLayout jPanelFilmHot4Layout = new javax.swing.GroupLayout(jPanelFilmHot4);
        jPanelFilmHot4.setLayout(jPanelFilmHot4Layout);
        jPanelFilmHot4Layout.setHorizontalGroup(
            jPanelFilmHot4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 401, Short.MAX_VALUE)
        );
        jPanelFilmHot4Layout.setVerticalGroup(
            jPanelFilmHot4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 103, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelFilmHotLayout = new javax.swing.GroupLayout(jPanelFilmHot);
        jPanelFilmHot.setLayout(jPanelFilmHotLayout);
        jPanelFilmHotLayout.setHorizontalGroup(
            jPanelFilmHotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFilmHotLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanelFilmHot1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelFilmHotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelFilmHot2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelFilmHot3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelFilmHot4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanelFilmHotLayout.setVerticalGroup(
            jPanelFilmHotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFilmHotLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFilmHotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanelFilmHot1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelFilmHotLayout.createSequentialGroup()
                        .addComponent(jPanelFilmHot2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanelFilmHot3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanelFilmHot4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        hotFilmPanel2.setText("Gợi ý");

        hotFilmPanel3.setText("Điểm số cao");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(80, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelFilmHot, javax.swing.GroupLayout.PREFERRED_SIZE, 1210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(hotFilmPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 1194, Short.MAX_VALUE)
                        .addComponent(hotFilmPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(hotFilmPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 715, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelFilmHot, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(hotFilmPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93)
                .addComponent(hotFilmPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(hotFilmPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonNextActionPerformed

    private void jButtonPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrevActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPrevActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Panel.HotFilmPanel hotFilmPanel1;
    private Panel.HotFilmPanel hotFilmPanel2;
    private Panel.HotFilmPanel hotFilmPanel3;
    private javax.swing.JButton jButtonNext;
    private javax.swing.JButton jButtonPrev;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelFilmHot;
    private javax.swing.JPanel jPanelFilmHot1;
    private javax.swing.JPanel jPanelFilmHot2;
    private javax.swing.JPanel jPanelFilmHot3;
    private javax.swing.JPanel jPanelFilmHot4;
    // End of variables declaration//GEN-END:variables
}
