/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Panel;

import ClassComponent.AccountData;
import ClassComponent.Movie;
import ClassExtend.CustomScrollBarUI;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author Admin
 */
public class HotFilmPanel extends javax.swing.JPanel {

    /**
     * Creates new form HotFilmPanel
     */
    private static String URL;
    private pnlXemtruoc panel;
    private Movie movie = new Movie();
    public HotFilmPanel() {
        initComponents();
    }

    public void setURL(String URL) {
        HotFilmPanel.URL = URL;
    }

    public void setPanelxemtruoc1Movie(List<Movie> mov)
    {
        pnlXemtruoc10.setAttribute(mov.get(0));
        pnlXemtruoc9.setAttribute(mov.get(1));
        pnlXemtruoc8.setAttribute(mov.get(2));
        pnlXemtruoc4.setAttribute(mov.get(3));
        /*pnlXemtruoc5.setAttribute(mov.get(4));
        pnlXemtruoc6.setAttribute(mov.get(5));
        pnlXemtruoc7.setAttribute(mov.get(6));
        pnlXemtruoc3.setAttribute(mov.get(7));
        pnlXemtruoc2.setAttribute(mov.get(8));
        pnlXemtruoc1.setAttribute(mov.get(9));   */
    }    

    public void setPanelxemtrc(JPanel panel) {
        pnlXemtruoc1.setParent(panel);
        pnlXemtruoc2.setParent(panel);
        pnlXemtruoc3.setParent(panel);
        pnlXemtruoc4.setParent(panel);
        pnlXemtruoc5.setParent(panel);
        pnlXemtruoc6.setParent(panel);
        pnlXemtruoc7.setParent(panel);
        pnlXemtruoc8.setParent(panel);
        pnlXemtruoc9.setParent(panel);
        pnlXemtruoc10.setParent(panel);   
    }
 
    public void setPanelThongtin(thongtin tt) {
        pnlXemtruoc1.setThongtin(tt);
        pnlXemtruoc2.setThongtin(tt);
        pnlXemtruoc3.setThongtin(tt);
        pnlXemtruoc4.setThongtin(tt);
        pnlXemtruoc5.setThongtin(tt);
        pnlXemtruoc6.setThongtin(tt);
        pnlXemtruoc7.setThongtin(tt);
        pnlXemtruoc8.setThongtin(tt);
        pnlXemtruoc9.setThongtin(tt);
        pnlXemtruoc10.setThongtin(tt);  
    }
    
    public void setFramexemtrc(HomeFrame Home) {
        pnlXemtruoc1.setHome(Home);
        pnlXemtruoc2.setHome(Home);
        pnlXemtruoc3.setHome(Home);
        pnlXemtruoc4.setHome(Home);
        pnlXemtruoc5.setHome(Home);
        pnlXemtruoc6.setHome(Home);
        pnlXemtruoc7.setHome(Home);
        pnlXemtruoc8.setHome(Home);
        pnlXemtruoc9.setHome(Home);
        pnlXemtruoc10.setHome(Home);   
    }
    
    public void setDanhgia(danhgia dg)
    {
        pnlXemtruoc1.setDanggia(dg);
        pnlXemtruoc2.setDanggia(dg);
        pnlXemtruoc3.setDanggia(dg);
        pnlXemtruoc4.setDanggia(dg);
        pnlXemtruoc5.setDanggia(dg);
        pnlXemtruoc6.setDanggia(dg);
        pnlXemtruoc7.setDanggia(dg);
        pnlXemtruoc8.setDanggia(dg);
        pnlXemtruoc9.setDanggia(dg);
        pnlXemtruoc10.setDanggia(dg);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanelScrol = new javax.swing.JPanel();
        pnlXemtruoc9 = new Panel.pnlXemtruoc();
        pnlXemtruoc10 = new Panel.pnlXemtruoc();
        pnlXemtruoc8 = new Panel.pnlXemtruoc();
        pnlXemtruoc4 = new Panel.pnlXemtruoc();
        pnlXemtruoc7 = new Panel.pnlXemtruoc();
        pnlXemtruoc6 = new Panel.pnlXemtruoc();
        pnlXemtruoc5 = new Panel.pnlXemtruoc();
        pnlXemtruoc2 = new Panel.pnlXemtruoc();
        pnlXemtruoc3 = new Panel.pnlXemtruoc();
        pnlXemtruoc1 = new Panel.pnlXemtruoc();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));

        jScrollPane1.setBackground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setBorder(null);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane1.getHorizontalScrollBar().setUI(new CustomScrollBarUI());

        jPanelScrol.setBackground(new java.awt.Color(0, 0, 0));
        jPanelScrol.setLayout(new java.awt.GridLayout(1, 10, 25, 0));
        jPanelScrol.add(pnlXemtruoc9);
        jPanelScrol.add(pnlXemtruoc10);
        jPanelScrol.add(pnlXemtruoc8);
        jPanelScrol.add(pnlXemtruoc4);
        jPanelScrol.add(pnlXemtruoc7);
        jPanelScrol.add(pnlXemtruoc6);
        jPanelScrol.add(pnlXemtruoc5);
        jPanelScrol.add(pnlXemtruoc2);
        jPanelScrol.add(pnlXemtruoc3);
        jPanelScrol.add(pnlXemtruoc1);

        jScrollPane1.setViewportView(jPanelScrol);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Phim hot");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1145, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void setText(String txt)
    {
        jLabel1.setText(txt);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanelScrol;
    private javax.swing.JScrollPane jScrollPane1;
    private Panel.pnlXemtruoc pnlXemtruoc1;
    private Panel.pnlXemtruoc pnlXemtruoc10;
    private Panel.pnlXemtruoc pnlXemtruoc2;
    private Panel.pnlXemtruoc pnlXemtruoc3;
    private Panel.pnlXemtruoc pnlXemtruoc4;
    private Panel.pnlXemtruoc pnlXemtruoc5;
    private Panel.pnlXemtruoc pnlXemtruoc6;
    private Panel.pnlXemtruoc pnlXemtruoc7;
    private Panel.pnlXemtruoc pnlXemtruoc8;
    private Panel.pnlXemtruoc pnlXemtruoc9;
    // End of variables declaration//GEN-END:variables
}
