package Panel;

import ClassComponent.Movie;
import java.util.List;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author Admin
 */
public class phim_yeuthich extends javax.swing.JPanel {

    /**
     * Creates new form phim_yeuthich
     */
    private HomeFrame home;
    private Movie movie = new Movie();

    public phim_yeuthich() {
        initComponents();
        
    }
    
    public void setHome(HomeFrame home)
    {
        this.home = home;
    }
    
    public void loadList(thongtin tt)
    {
        List<Movie> lstM = movie.getWatchList(home.getAccount().getID());
        for(int i =0;i<lstM.size();i++)
        {
            panel_con p = new panel_con();
            p.setContent(lstM.get(i).getName(), lstM.get(i).getUrlPoster());
            p.setComponent(home, lstM.get(i), tt);
            home.phim_yeuthich1.add(p);  
        }
        home.phim_yeuthich1.repaint();
        home.phim_yeuthich1.revalidate();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(0, 0, 0));
        setMaximumSize(new java.awt.Dimension(1100, 32767));
        setMinimumSize(new java.awt.Dimension(1000, 10));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
