/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Panel;

import ClassComponent.AccountData;
import ClassExtend.ImageBackGround;
import ClassExtend.PanelCustom;

/**
 *
 * @author Admin
 */
public class pnlThongtin extends javax.swing.JPanel {

    /**
     * Creates new form pnlThongtin
     */
    private AccountData account = new AccountData();
    
    public pnlThongtin() {
        initComponents();
    }
    
    public void chgpnlThongtin(AccountData acc)
    {
        this.account = acc;
        setField();
    }

    public void setField()
    {
        jTextFieldGender.setText(account.getGender());
        jTextFieldTentaikhoan.setText(account.getName());
        jTextFieldBirth.setText(String.valueOf(account.getAge()));
        jTextFieldPhonenum.setText(account.getPhoneNum());
        jTextFieldmail.setText(account.getMail());
        jPanelAvatar = new PanelCustom(0, null, 0, account.getURLAva(),true);
        jPanelAvatar.repaint();
        jPanelTheme = new PanelCustom(0, null, 0, account.getURLTheme(),true);
        jPanelTheme.repaint();
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanelAvatar = new javax.swing.JPanel();
        jPanelTheme = new javax.swing.JPanel();
        jPanelthongtintk = new javax.swing.JPanel();
        jLabeltttk = new javax.swing.JLabel();
        jLabeltttk2 = new javax.swing.JLabel();
        jLabeltttk3 = new javax.swing.JLabel();
        jLabeltttk4 = new javax.swing.JLabel();
        jLabeltttk5 = new javax.swing.JLabel();
        jLabeltttk6 = new javax.swing.JLabel();
        jLabeldoiten = new javax.swing.JLabel();
        jTextFieldmail = new javax.swing.JTextField();
        jTextFieldPhonenum = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jTextFieldBirth = new javax.swing.JTextField();
        jTextFieldGender = new javax.swing.JTextField();
        jLabeldoimk = new javax.swing.JLabel();
        jLabelcapnhatns = new javax.swing.JLabel();
        jLabelcapnhatgt = new javax.swing.JLabel();
        jPasswordField2 = new javax.swing.JPasswordField();
        jLabeltttk11 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabeltttk12 = new javax.swing.JLabel();
        jPaneltaikhoanlienket = new javax.swing.JPanel();
        jLabeltttk8 = new javax.swing.JLabel();
        jPanel5 = new ImageBackGround("C:\\Java\\FinalPresent\\src\\main\\java\\Icon\\facebook.png");
        jPanel6 = new ImageBackGround("C:\\Java\\FinalPresent\\src\\main\\java\\Icon\\google.png");
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabellienketfb = new javax.swing.JLabel();
        jLabellienketgg = new javax.swing.JLabel();
        jPanelquanlynguoidung = new javax.swing.JPanel();
        jLabeltttk9 = new javax.swing.JLabel();
        jPanel4 = new ImageBackGround("C:\\Java\\FinalPresent\\src\\main\\java\\Icon\\lien.png");
        jLabelqlinguoidung = new javax.swing.JLabel();
        jLabeltttk10 = new javax.swing.JLabel();
        jPanelcaidat = new javax.swing.JPanel();
        jLabeltttk7 = new javax.swing.JLabel();
        jLabelcaidat = new javax.swing.JLabel();
        jLabelcaidat1 = new javax.swing.JLabel();
        jLabelcaidat2 = new javax.swing.JLabel();
        jLabelcaidatt = new javax.swing.JLabel();
        jLabelcaidatt1 = new javax.swing.JLabel();
        jLabelcaidatt2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldTentaikhoan = new javax.swing.JTextField();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelAvatar.setBackground(new java.awt.Color(0, 204, 51));

        javax.swing.GroupLayout jPanelAvatarLayout = new javax.swing.GroupLayout(jPanelAvatar);
        jPanelAvatar.setLayout(jPanelAvatarLayout);
        jPanelAvatarLayout.setHorizontalGroup(
            jPanelAvatarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanelAvatarLayout.setVerticalGroup(
            jPanelAvatarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel2.add(jPanelAvatar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, -1, -1));

        jPanelTheme.setBackground(new java.awt.Color(204, 255, 102));

        javax.swing.GroupLayout jPanelThemeLayout = new javax.swing.GroupLayout(jPanelTheme);
        jPanelTheme.setLayout(jPanelThemeLayout);
        jPanelThemeLayout.setHorizontalGroup(
            jPanelThemeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1020, Short.MAX_VALUE)
        );
        jPanelThemeLayout.setVerticalGroup(
            jPanelThemeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );

        jPanel2.add(jPanelTheme, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 140));

        jPanelthongtintk.setBackground(new java.awt.Color(255, 255, 255));
        jPanelthongtintk.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 0, new java.awt.Color(204, 204, 204)));

        jLabeltttk.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabeltttk.setText("Thông tin tài khoản");

        jLabeltttk2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabeltttk2.setText("Email:");

        jLabeltttk3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabeltttk3.setText("Số điện thoại:");

        jLabeltttk4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabeltttk4.setText("Mật khẩu:");

        jLabeltttk5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabeltttk5.setText("Ngày sinh:");

        jLabeltttk6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabeltttk6.setText("Giới tính:");

        jLabeldoiten.setBackground(new java.awt.Color(255, 255, 255));
        jLabeldoiten.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabeldoiten.setForeground(new java.awt.Color(0, 204, 102));
        jLabeldoiten.setText("Đổi tên");
        jLabeldoiten.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabeldoitenMouseClicked(evt);
            }
        });

        jTextFieldmail.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTextFieldmail.setText(account.getMail());
        jTextFieldmail.setBorder(null);
        jTextFieldmail.setCaretColor(new java.awt.Color(255, 255, 255));
        jTextFieldmail.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldmail.setEnabled(false);

        jTextFieldPhonenum.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTextFieldPhonenum.setText(account.getPhoneNum());
        jTextFieldPhonenum.setBorder(null);
        jTextFieldPhonenum.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldPhonenum.setEnabled(false);

        jPasswordField1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jPasswordField1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });

        jTextFieldBirth.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTextFieldBirth.setText(String.valueOf(account.getAge()));
        jTextFieldBirth.setBorder(null);
        jTextFieldBirth.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldBirth.setEnabled(false);
        jTextFieldBirth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBirthActionPerformed(evt);
            }
        });

        jTextFieldGender.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTextFieldGender.setText(account.getGender());
        jTextFieldGender.setBorder(null);
        jTextFieldGender.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldGender.setEnabled(false);
        jTextFieldGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldGenderActionPerformed(evt);
            }
        });

        jLabeldoimk.setBackground(new java.awt.Color(255, 255, 255));
        jLabeldoimk.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabeldoimk.setForeground(new java.awt.Color(0, 204, 102));
        jLabeldoimk.setText("Đổi mật khẩu");
        jLabeldoimk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabeldoimkMouseClicked(evt);
            }
        });

        jLabelcapnhatns.setBackground(new java.awt.Color(255, 255, 255));
        jLabelcapnhatns.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabelcapnhatns.setForeground(new java.awt.Color(0, 204, 102));
        jLabelcapnhatns.setText("Cập nhật ngày sinh");
        jLabelcapnhatns.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelcapnhatnsMouseClicked(evt);
            }
        });

        jLabelcapnhatgt.setBackground(new java.awt.Color(255, 255, 255));
        jLabelcapnhatgt.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabelcapnhatgt.setForeground(new java.awt.Color(0, 204, 102));
        jLabelcapnhatgt.setText("Cập nhật giới tính");
        jLabelcapnhatgt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelcapnhatgtMouseClicked(evt);
            }
        });

        jPasswordField2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jPasswordField2.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jPasswordField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField2ActionPerformed(evt);
            }
        });

        jLabeltttk11.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabeltttk11.setText("Xác nhận mật khẩu");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabeltttk12.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabeltttk12.setText("Mật khẩu:");

        javax.swing.GroupLayout jPanelthongtintkLayout = new javax.swing.GroupLayout(jPanelthongtintk);
        jPanelthongtintk.setLayout(jPanelthongtintkLayout);
        jPanelthongtintkLayout.setHorizontalGroup(
            jPanelthongtintkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelthongtintkLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabeltttk, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79)
                .addGroup(jPanelthongtintkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelthongtintkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabeltttk2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabeltttk3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabeltttk5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabeltttk6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabeltttk11)
                    .addComponent(jLabeltttk12, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(94, 94, 94)
                .addGroup(jPanelthongtintkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldmail)
                    .addComponent(jTextFieldPhonenum)
                    .addComponent(jPasswordField1)
                    .addComponent(jTextFieldBirth)
                    .addComponent(jTextFieldGender, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabeltttk4, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1)
                .addGap(18, 18, 18)
                .addGroup(jPanelthongtintkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelcapnhatns, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelthongtintkLayout.createSequentialGroup()
                        .addComponent(jLabeldoimk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(80, 80, 80))
                    .addComponent(jLabeldoiten, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelcapnhatgt, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelthongtintkLayout.setVerticalGroup(
            jPanelthongtintkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelthongtintkLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelthongtintkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelthongtintkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabeltttk)
                        .addComponent(jLabeldoiten))
                    .addGroup(jPanelthongtintkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanelthongtintkLayout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addComponent(jLabelcapnhatns)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabelcapnhatgt))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelthongtintkLayout.createSequentialGroup()
                            .addGap(23, 23, 23)
                            .addGroup(jPanelthongtintkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabeltttk2)
                                .addComponent(jTextFieldmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanelthongtintkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabeltttk3)
                                .addComponent(jTextFieldPhonenum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanelthongtintkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabeldoimk)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabeltttk4)
                                .addComponent(jLabeltttk12))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanelthongtintkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabeltttk11))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanelthongtintkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabeltttk5)
                                .addComponent(jTextFieldBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanelthongtintkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabeltttk6)
                                .addComponent(jTextFieldGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(20, 20, 20))
        );

        jPaneltaikhoanlienket.setBackground(new java.awt.Color(255, 255, 255));
        jPaneltaikhoanlienket.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));

        jLabeltttk8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabeltttk8.setText("Tài khoản liên kết");

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel1.setText("Facebook");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel2.setText("Google");

        jLabellienketfb.setBackground(new java.awt.Color(255, 255, 255));
        jLabellienketfb.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabellienketfb.setForeground(new java.awt.Color(0, 204, 102));
        jLabellienketfb.setText("Liên kết");
        jLabellienketfb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabellienketfbMouseClicked(evt);
            }
        });

        jLabellienketgg.setBackground(new java.awt.Color(255, 255, 255));
        jLabellienketgg.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabellienketgg.setForeground(new java.awt.Color(0, 204, 102));
        jLabellienketgg.setText("Liên kết");
        jLabellienketgg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabellienketggMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPaneltaikhoanlienketLayout = new javax.swing.GroupLayout(jPaneltaikhoanlienket);
        jPaneltaikhoanlienket.setLayout(jPaneltaikhoanlienketLayout);
        jPaneltaikhoanlienketLayout.setHorizontalGroup(
            jPaneltaikhoanlienketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneltaikhoanlienketLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabeltttk8, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addGroup(jPaneltaikhoanlienketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPaneltaikhoanlienketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(324, 324, 324)
                .addGroup(jPaneltaikhoanlienketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabellienketfb)
                    .addComponent(jLabellienketgg))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPaneltaikhoanlienketLayout.setVerticalGroup(
            jPaneltaikhoanlienketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneltaikhoanlienketLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPaneltaikhoanlienketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPaneltaikhoanlienketLayout.createSequentialGroup()
                        .addGroup(jPaneltaikhoanlienketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPaneltaikhoanlienketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabeltttk8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPaneltaikhoanlienketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPaneltaikhoanlienketLayout.createSequentialGroup()
                        .addComponent(jLabellienketfb, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabellienketgg)))
                .addGap(20, 20, 20))
        );

        jPanelquanlynguoidung.setBackground(new java.awt.Color(255, 255, 255));
        jPanelquanlynguoidung.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));

        jLabeltttk9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabeltttk9.setText("Quản lý người dùng");

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        jLabelqlinguoidung.setBackground(new java.awt.Color(255, 255, 255));
        jLabelqlinguoidung.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabelqlinguoidung.setForeground(new java.awt.Color(0, 204, 102));
        jLabelqlinguoidung.setText("Chỉnh sửa người dùng");
        jLabelqlinguoidung.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelqlinguoidungMouseClicked(evt);
            }
        });

        jLabeltttk10.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabeltttk10.setText("Thúy Liên");

        javax.swing.GroupLayout jPanelquanlynguoidungLayout = new javax.swing.GroupLayout(jPanelquanlynguoidung);
        jPanelquanlynguoidung.setLayout(jPanelquanlynguoidungLayout);
        jPanelquanlynguoidungLayout.setHorizontalGroup(
            jPanelquanlynguoidungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelquanlynguoidungLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabeltttk9, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addGroup(jPanelquanlynguoidungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabeltttk10, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelquanlynguoidungLayout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(419, 419, 419)
                        .addComponent(jLabelqlinguoidung, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(131, Short.MAX_VALUE))
        );
        jPanelquanlynguoidungLayout.setVerticalGroup(
            jPanelquanlynguoidungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelquanlynguoidungLayout.createSequentialGroup()
                .addGroup(jPanelquanlynguoidungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelquanlynguoidungLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabeltttk9))
                    .addGroup(jPanelquanlynguoidungLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanelquanlynguoidungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelqlinguoidung)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabeltttk10)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanelcaidat.setBackground(new java.awt.Color(255, 255, 255));
        jPanelcaidat.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(204, 204, 204)));

        jLabeltttk7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabeltttk7.setText("Cài đặt");

        jLabelcaidat.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelcaidat.setText("Nhận thông báo từ QLS:");

        jLabelcaidat1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelcaidat1.setText("Lịch sử xem:");

        jLabelcaidat2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelcaidat2.setText("Lịch sử tìm kiếm:");

        jLabelcaidatt.setBackground(new java.awt.Color(255, 255, 255));
        jLabelcaidatt.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabelcaidatt.setForeground(new java.awt.Color(0, 204, 102));
        jLabelcaidatt.setText("Tắt");
        jLabelcaidatt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelcaidattMouseClicked(evt);
            }
        });

        jLabelcaidatt1.setBackground(new java.awt.Color(255, 255, 255));
        jLabelcaidatt1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabelcaidatt1.setForeground(new java.awt.Color(0, 204, 102));
        jLabelcaidatt1.setText("Xóa");
        jLabelcaidatt1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelcaidatt1MouseClicked(evt);
            }
        });

        jLabelcaidatt2.setBackground(new java.awt.Color(255, 255, 255));
        jLabelcaidatt2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabelcaidatt2.setForeground(new java.awt.Color(0, 204, 102));
        jLabelcaidatt2.setText("Xóa");
        jLabelcaidatt2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelcaidatt2MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 203, 129));
        jLabel3.setText("Xem lịch sử");

        javax.swing.GroupLayout jPanelcaidatLayout = new javax.swing.GroupLayout(jPanelcaidat);
        jPanelcaidat.setLayout(jPanelcaidatLayout);
        jPanelcaidatLayout.setHorizontalGroup(
            jPanelcaidatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelcaidatLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabeltttk7, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(jPanelcaidatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelcaidat, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelcaidat2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelcaidat1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 386, Short.MAX_VALUE)
                .addGroup(jPanelcaidatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabelcaidatt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelcaidatt1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelcaidatt2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(169, 169, 169))
        );
        jPanelcaidatLayout.setVerticalGroup(
            jPanelcaidatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelcaidatLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelcaidatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabeltttk7)
                    .addComponent(jLabelcaidat)
                    .addComponent(jLabelcaidatt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelcaidatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelcaidat1)
                    .addComponent(jLabelcaidatt1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelcaidatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelcaidat2)
                    .addComponent(jLabelcaidatt2))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jTextFieldTentaikhoan.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jTextFieldTentaikhoan.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldTentaikhoan.setText(account.getName());
        jTextFieldTentaikhoan.setBorder(null);
        jTextFieldTentaikhoan.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldTentaikhoan.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelquanlynguoidung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPaneltaikhoanlienket, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanelthongtintk, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanelcaidat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextFieldTentaikhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldTentaikhoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelthongtintk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPaneltaikhoanlienket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanelquanlynguoidung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanelcaidat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jLabeldoitenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabeldoitenMouseClicked
        // TODO add your handling code here:
        jTextFieldTentaikhoan.setEnabled(true); // Cho phép chỉnh sửa
        jTextFieldTentaikhoan.requestFocus(); // Đặt con trỏ vào ô nhập
    }//GEN-LAST:event_jLabeldoitenMouseClicked

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
        jPasswordField1.setEnabled(false); // Cho phép chỉnh sửa
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jTextFieldBirthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBirthActionPerformed
        // TODO add your handling code here:
        //jTextFieldBirth.setEnabled(false);
    }//GEN-LAST:event_jTextFieldBirthActionPerformed

    private void jTextFieldGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldGenderActionPerformed
        // TODO add your handling code here:
        //jTextFieldGender.setEnabled(false);
    }//GEN-LAST:event_jTextFieldGenderActionPerformed

    private void jLabeldoimkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabeldoimkMouseClicked
        // TODO add your handling code here:
        jPasswordField1.setEnabled(true); // Cho phép chỉnh sửa
        jPasswordField2.setEnabled(true);
        jPasswordField1.requestFocus(); // Đặt con trỏ vào ô nhập
    }//GEN-LAST:event_jLabeldoimkMouseClicked

    private void jLabelcapnhatnsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelcapnhatnsMouseClicked
        // TODO add your handling code here:
        jTextFieldBirth.setEnabled(true); // Cho phép chỉnh sửa
        jTextFieldBirth.requestFocus(); // Đặt con trỏ vào ô nhập
    }//GEN-LAST:event_jLabelcapnhatnsMouseClicked

    private void jLabelcapnhatgtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelcapnhatgtMouseClicked
        // TODO add your handling code here:
        jTextFieldGender.setEnabled(true); // Cho phép chỉnh sửa
        jTextFieldGender.requestFocus(); // Đặt con trỏ vào ô nhập
    }//GEN-LAST:event_jLabelcapnhatgtMouseClicked

    private void jLabellienketfbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabellienketfbMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabellienketfbMouseClicked

    private void jLabellienketggMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabellienketggMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabellienketggMouseClicked

    private void jLabelqlinguoidungMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelqlinguoidungMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelqlinguoidungMouseClicked

    private void jLabelcaidattMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelcaidattMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelcaidattMouseClicked

    private void jLabelcaidatt1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelcaidatt1MouseClicked
        // TODO add your handling code here: 
    }//GEN-LAST:event_jLabelcaidatt1MouseClicked

    private void jLabelcaidatt2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelcaidatt2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelcaidatt2MouseClicked

    private void jPasswordField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelcaidat;
    private javax.swing.JLabel jLabelcaidat1;
    private javax.swing.JLabel jLabelcaidat2;
    private javax.swing.JLabel jLabelcaidatt;
    private javax.swing.JLabel jLabelcaidatt1;
    private javax.swing.JLabel jLabelcaidatt2;
    private javax.swing.JLabel jLabelcapnhatgt;
    private javax.swing.JLabel jLabelcapnhatns;
    private javax.swing.JLabel jLabeldoimk;
    private javax.swing.JLabel jLabeldoiten;
    private javax.swing.JLabel jLabellienketfb;
    private javax.swing.JLabel jLabellienketgg;
    private javax.swing.JLabel jLabelqlinguoidung;
    private javax.swing.JLabel jLabeltttk;
    private javax.swing.JLabel jLabeltttk10;
    private javax.swing.JLabel jLabeltttk11;
    private javax.swing.JLabel jLabeltttk12;
    private javax.swing.JLabel jLabeltttk2;
    private javax.swing.JLabel jLabeltttk3;
    private javax.swing.JLabel jLabeltttk4;
    private javax.swing.JLabel jLabeltttk5;
    private javax.swing.JLabel jLabeltttk6;
    private javax.swing.JLabel jLabeltttk7;
    private javax.swing.JLabel jLabeltttk8;
    private javax.swing.JLabel jLabeltttk9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanelAvatar;
    private javax.swing.JPanel jPanelTheme;
    private javax.swing.JPanel jPanelcaidat;
    private javax.swing.JPanel jPanelquanlynguoidung;
    private javax.swing.JPanel jPaneltaikhoanlienket;
    private javax.swing.JPanel jPanelthongtintk;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextFieldBirth;
    private javax.swing.JTextField jTextFieldGender;
    private javax.swing.JTextField jTextFieldPhonenum;
    private javax.swing.JTextField jTextFieldTentaikhoan;
    private javax.swing.JTextField jTextFieldmail;
    // End of variables declaration//GEN-END:variables
}
