/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Panel;
import ClassComponent.Movie;
import ClassExtend.TranslucentPanel;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import uk.co.caprica.vlcj.player.component.EmbeddedMediaPlayerComponent;

/**
 *
 * @author Admin
 */
public class WatchPanel extends javax.swing.JPanel {

    /**
     * Creates new form WatchPanel
     */
    
    private static String URL;
    private EmbeddedMediaPlayerComponent mediaPlayerComponent;
    private static boolean isFullscreen;
    private static Dimension originalSize;
    private static JPanel originalParent;
    public WatchPanel() {
        
        System.setProperty("jna.library.path", "C:\\Java\\FinalPresent\\VideoLAN\\VLC");
        initComponents();

    }

    
    public void releaseMedia() {
        mediaPlayerComponent.mediaPlayer().release();
    }
    
    public void setURL(String URL) {
        this.URL = URL;
    }
    
    public void setTitle(String name)
    {
        jLabelTitle.setText(name);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jButtonStart = new javax.swing.JButton();
        jButtonPlay = new javax.swing.JButton();
        jButtonPause = new javax.swing.JButton();
        jButtonStop = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabelTitle = new javax.swing.JLabel();
        jPanelRating = new javax.swing.JPanel();
        jPanelRecomment = new javax.swing.JPanel();
        hotFilmPanel1 = new Panel.HotFilmPanel();

        setBackground(new java.awt.Color(51, 51, 51));
        setMinimumSize(new java.awt.Dimension(1293, 0));

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel5MouseExited(evt);
            }
        });

        jButtonStart.setText("Start");
        jButtonStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStartActionPerformed(evt);
            }
        });
        jPanel5.add(jButtonStart);

        jButtonPlay.setText("Play");
        jButtonPlay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonPlayMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonPlayMouseExited(evt);
            }
        });
        jButtonPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlayActionPerformed(evt);
            }
        });
        jPanel5.add(jButtonPlay);

        jButtonPause.setText("Pause");
        jButtonPause.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonPlayMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonPlayMouseExited(evt);
            }
        });
        jButtonPause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPauseActionPerformed(evt);
            }
        });
        jPanel5.add(jButtonPause);

        jButtonStop.setText("Stop");
        jButtonStop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonPlayMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonPlayMouseExited(evt);
            }
        });
        jButtonStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStopActionPerformed(evt);
            }
        });
        jPanel5.add(jButtonStop);

        jPanel1.setLayout(new java.awt.BorderLayout());
        mediaPlayerComponent = new EmbeddedMediaPlayerComponent();
        jPanel1.add(mediaPlayerComponent, BorderLayout.CENTER);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1171, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.addComponentListener(new ComponentAdapter() {
            @Override
            public void componentShown(ComponentEvent e) {
                // Bắt đầu phát video khi jPanelPart đã hiển thị đầy đủ
                mediaPlayerComponent.mediaPlayer().media().prepare(URL);
                //mediaPlayerComponent.mediaPlayer().controls().play();
                //mediaPlayerComponent.mediaPlayer().controls().play();
                jPanel1.repaint();
                jPanel1.revalidate();
            }
        });

        jLabelTitle.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitle.setText("Tên Phim");

        javax.swing.GroupLayout jPanelRatingLayout = new javax.swing.GroupLayout(jPanelRating);
        jPanelRating.setLayout(jPanelRatingLayout);
        jPanelRatingLayout.setHorizontalGroup(
            jPanelRatingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 855, Short.MAX_VALUE)
        );
        jPanelRatingLayout.setVerticalGroup(
            jPanelRatingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelRecommentLayout = new javax.swing.GroupLayout(jPanelRecomment);
        jPanelRecomment.setLayout(jPanelRecommentLayout);
        jPanelRecommentLayout.setHorizontalGroup(
            jPanelRecommentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelRecommentLayout.setVerticalGroup(
            jPanelRecommentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 374, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(74, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelRating, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jPanelRecomment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(hotFilmPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelRecomment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelRating, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(36, 36, 36)
                .addComponent(hotFilmPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    
    private void jButtonPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlayActionPerformed
        // TODO add your handling code here:
        //mediaPlayerComponent.mediaPlayer().media().play(URL);
        playMedia();
        
    }//GEN-LAST:event_jButtonPlayActionPerformed

    private void jButtonPauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPauseActionPerformed
        // TODO add your handling code here:
        pauseMedia();
    }//GEN-LAST:event_jButtonPauseActionPerformed

    private void jButtonStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStopActionPerformed
        // TODO add your handling code here:
        stopMedia();
    }//GEN-LAST:event_jButtonStopActionPerformed

    private void jButtonPlayMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonPlayMouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_jButtonPlayMouseEntered

    private void jButtonPlayMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonPlayMouseExited
        // TODO add your handling code here:

    }//GEN-LAST:event_jButtonPlayMouseExited

    private void jPanel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_jPanel5MouseEntered

    private void jPanel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseExited
        // TODO add your handling code here:

    }//GEN-LAST:event_jPanel5MouseExited

    private void jButtonStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStartActionPerformed
        // TODO add your handling code here:
        mediaPlayerComponent.mediaPlayer().media().play(URL);
        playMedia();
        repaint();
        revalidate();
    }//GEN-LAST:event_jButtonStartActionPerformed
    
    public void setListMovie(List<Movie> movies)
    {
        hotFilmPanel1.setPanelxemtruoc1Movie(movies);
    }
    
    private void toggleFullscreen() 
    { 
        JFrame topFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
        if (isFullscreen) {
            // Quay trở lại kích thước ban đầu
            topFrame.getContentPane().remove(this);
            originalParent.add(this);
            setPreferredSize(originalSize);
            originalParent.revalidate();
            originalParent.repaint();
            isFullscreen = false;
        } else {
            // Chuyển sang chế độ toàn màn hình
            originalParent = (JPanel) getParent();
            originalSize = getSize();
            topFrame.getContentPane().removeAll();
            topFrame.getContentPane().add(this, BorderLayout.CENTER);
            setPreferredSize(topFrame.getSize());
            topFrame.revalidate();
            topFrame.repaint();
            isFullscreen = true;
        }
    }
    
    public void startMedia(String mediaPath) 
    {
        mediaPlayerComponent.mediaPlayer().media().startPaused(mediaPath);
        
    }
    
    public void playMedia() 
    {
        mediaPlayerComponent.mediaPlayer().controls().play();
    }
    
    public void pauseMedia() 
    {
        mediaPlayerComponent.mediaPlayer().controls().pause();
    }
    
    public void stopMedia() 
    {
        mediaPlayerComponent.mediaPlayer().controls().stop();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Panel.HotFilmPanel hotFilmPanel1;
    private javax.swing.JButton jButtonPause;
    private javax.swing.JButton jButtonPlay;
    private javax.swing.JButton jButtonStart;
    private javax.swing.JButton jButtonStop;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanelRating;
    private javax.swing.JPanel jPanelRecomment;
    // End of variables declaration//GEN-END:variables
}
